on: 
  workflow_call:
    inputs:
      force:
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        default: false
env:
  inputs: ${{ toJson(github.event.inputs || inputs) }}
jobs:
  dependency:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@master
    - uses: pnpm/action-setup@master
      with:
        version: latest
    - uses: actions/setup-node@main
      with:
        node-version: latest
        cache: 'pnpm'
    - if: fromJson(env.inputs).force != false
      run: pnpm install --force
    - run: pnpm install
