on: 
  workflow_call:
    inputs:
      clean:
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      clean:
        type: boolean
        default: false
env:
  inputs: ${{ toJson(github.event.inputs || inputs) }}
jobs:
  dependency:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - uses: actions/checkout@master
    - id: node-cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ github.repository }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.repository }}-node-modules-
    - if: fromJson(env.inputs).clean != false
      run: yarn cache clean
    - if: steps.node-cache.outputs.cache-hit != 'true' || fromJson(env.inputs).clean != false
      run: yarn install
