on:
  workflow_call:
    inputs:
      prev:
        type: string
        default: '[ "fetch" ]'
      which:
        type: string
        default: '[ { "text": "vaccination", "emoji": "💉" } , { "text": "case", "emoji": "🦠" } ]'
  workflow_dispatch:
    inputs:
      prev:
        type: string
        default: '[ "" ]'
      which:
        type: string
        default: '[ { "text": "vaccination", "emoji": "💉" } , { "text": "case", "emoji": "🦠" } ]'
jobs:
  plain:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        prev: ${{ fromJson((github.event.inputs || inputs).prev) }}
        which: ${{ fromJson((github.event.inputs || inputs).which) }}
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@master
    - uses: pnpm/action-setup@master
      with:
        version: latest
    - uses: actions/setup-node@main
      with:
        node-version: 16
        cache: 'pnpm'
    - run: pnpm install
    - uses: actions/download-artifact@v2
      if: ${{ matrix.prev != '' }}
      with:
        name: artifact-${{ matrix.which.text }}
        path: ./
    - if: ${{ matrix.prev != '' }}
      run: tar -zxvf ${{ matrix.prev }}-${{ matrix.which.text }}.tar.gz
    - run: pnpm plain:${{ matrix.which.text }}
    - run: |
        tar -zcvf \
          plain-${{ matrix.which.text }}.tar.gz \
          ./plain/${{ matrix.which.text }}/*
    - uses: actions/upload-artifact@v2
      with:
        name: artifact-${{ matrix.which.text }}
        path: plain-${{ matrix.which.text }}.tar.gz
    # THIS WILL RUN WHILE RUN BY WORKFLOW_DISPATCH
    - uses: corcc/publish@node
      if: ${{ github.event_name == 'workflow_dispatch' }}
      with:
        TZ: 'Asia/Seoul'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        TASK_NAME: ⬆️${{ matrix.which.emoji }}📄
