on:
  workflow_call:
    inputs:
      prev:
        type: string
        default: '[ "plain" ]'
      day:
        type: string
        default: '[ "today" ]'
      which:
        type: string
        default: '[ "vaccination", "case" ]'
    secrets:
      SLACK_TOKEN:
        required: true
      SLACK_TODAY:
        required: true
  workflow_dispatch:
    inputs:
      prev:
        type: string
        default: '[ "" ]'
      day:
        type: string
        default: '[ "today" ]'
      which:
        type: string
        default: '[ "vaccination", "case" ]'
jobs:
  slack:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      matrix:
        prev: ${{ fromJson((github.event.inputs || inputs).prev) }}
        which: ${{ fromJson((github.event.inputs || inputs).which) }}
        day: ${{ fromJson((github.event.inputs || inputs).day) }}
    steps:
    - uses: actions/checkout@master
    - uses: pnpm/action-setup@master
      with:
        version: 8
    - uses: actions/setup-node@main
      with:
        node-version: 16
        cache: 'pnpm'
    - run: pnpm install --no-frozen-lockfile
    - id: before
      run: echo "::set-output name=hash::${{ hashFiles('./plain/**') }}"
    - uses: actions/download-artifact@v2
      if: ${{ matrix.prev != '' }}
      with:
        name: artifact-${{ matrix.which }}
        path: ./
    - if: ${{ matrix.prev != '' }}
      run: tar -zxvf ${{ matrix.prev }}-${{ matrix.which }}.tar.gz
    - id: after
      run: echo "::set-output name=hash::${{ hashFiles('./plain/**') }}"
    - run: echo "diff"
      env:
        result: ${{ steps.before.outputs.hash != steps.after.outputs.hash }}
    - run: echo "event_name"
      env:
        result: ${{ github.event_name }}
    - env:
        SLACK_CHANNEL: ${{ secrets.SLACK_TODAY }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      if: ${{ steps.before.outputs.hash != steps.after.outputs.hash || (github.event_name != 'schedule' && github.event_name != 'push') }}
      run: pnpm slack:${{ matrix.day }}:${{ matrix.which }}
