name: TSLint
on: 
  workflow_dispatch:
  push:
jobs:
  install:
    name: Install 🟢
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - name: Cache node_modules 🔧⚙️🟢
      uses: actions/cache@v2
      id: cache-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-modules
    - name: Install 🟢
      run: yarn install
    
  tslint:
    name: TSLint 
    needs: install
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - name: Cache node_modules 🔧⚙️🟢
      uses: actions/cache@v2
      id: cache-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-modules
    - name: Check TSLint
      run: yarn tslint