on: 
  workflow_call:
    inputs:
      prev:
        type: string
        default: '[ "plain" ]'
      day:
        type: string
        default: '[ "today" ]'
      which: 
        type: string
        default: '[ "vaccination", "case" ]'
    secrets:
      TWITTER_CONSUMER_KEY:
        required: false
      TWITTER_CONSUMER_SECRET:
        required: false
      TWITTER_ACCESS_TOKEN_KEY:
        required: false
      TWITTER_ACCESS_TOKEN_SECRET: 
        required: false
  workflow_dispatch:
    inputs:
      prev:
        type: string
        default: '[ "" ]'
      day:
        type: string
        default: '[ "today" ]'
      which: 
        type: string
        default: '[ "vaccination", "case" ]'
jobs:
  tweet:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      matrix:
        prev: ${{ fromJson((github.event.inputs || inputs).prev) }}
        which: ${{ fromJson((github.event.inputs || inputs).which) }}
        day: ${{ fromJson((github.event.inputs || inputs).day) }}
    steps:
    - uses: actions/checkout@master
    - uses: pnpm/action-setup@master
      with:
        version: latest
    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
        cache: 'pnpm'
    - run: pnpm install
    - id: before
      run: echo "::set-output name=hash::${{ hashFiles('./plain/**') }}"
    - uses: actions/download-artifact@v2
      if: ${{ matrix.prev != '' }}
      with:
        name: artifact-${{ matrix.which }}
        path: ./
    - if: ${{ matrix.prev != '' }}
      run: tar -zxvf ${{ matrix.prev }}-${{ matrix.which }}.tar.gz
    - id: after
      run: echo "::set-output name=hash::${{ hashFiles('./plain/**') }}"
    - run: echo "diff"
      env:
        result: ${{ steps.before.outputs.hash != steps.after.outputs.hash }}
    - run: echo "event_name"
      env:
        result: ${{ github.event_name }}
    - run: pnpm tweet:${{ matrix.day }}:${{ matrix.which }}
      if: ${{ steps.before.outputs.hash != steps.after.outputs.hash || (github.event_name != 'schedule' && github.event_name != 'push') }}
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
