on: 
  workflow_call:
    inputs:
      prev:
        type: string
        default: '[ "plain" ]'
      day:
        type: string
        default: '[ "today" ]'
      which: 
        type: string
        default: '[ "vaccination", "case" ]'
    secrets:
      TWITTER_CONSUMER_KEY:
        required: false
      TWITTER_CONSUMER_SECRET:
        required: false
      TWITTER_ACCESS_TOKEN_KEY:
        required: false
      TWITTER_ACCESS_TOKEN_SECRET: 
        required: false
  workflow_dispatch:
    inputs:
      prev:
        type: string
        default: '[ "" ]'
      day:
        type: string
        default: '[ "today" ]'
      which: 
        type: string
        default: '[ "vaccination", "case" ]'
jobs:
  tweet:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      matrix:
        prev: ${{ fromJson((github.event.inputs || inputs).prev) }}
        which: ${{ fromJson((github.event.inputs || inputs).which) }}
        day: ${{ fromJson((github.event.inputs || inputs).day) }}
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - uses: actions/checkout@master
    - id: node-cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ github.repository }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.repository }}-node-modules-
    - if: steps.node-cache.outputs.cache-hit != 'true'
      run: yarn install
    - id: before
      run: echo "::set-output name=hash::${{ hashFiles('./plain/**') }}"
    - uses: actions/download-artifact@v2
      if: ${{ matrix.prev != '' }}
      with:
        name: artifact-${{ matrix.which }}
        path: ./
    - if: ${{ matrix.prev != '' }}
      run: tar -zxvf ${{ matrix.prev }}-${{ matrix.which }}.tar.gz
    - id: after
      run: echo "::set-output name=hash::${{ hashFiles('./plain/**') }}"
    - run: echo "diff"
      env:
        result: ${{ steps.before.outputs.hash != steps.after.outputs.hash }}
    - run: echo "event_name"
      env:
        result: ${{ github.event_name }}
    - run: yarn tweet:${{ matrix.day }}:${{ matrix.which }}
      if: ${{ steps.before.outputs.hash != steps.after.outputs.hash || (github.event_name != 'schedule' && github.event_name != 'push') }}
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
